### ISSUE TITLE
Make Tempomat Keep Speed

### ISSUE THREAD

**Issue by aether-fox** [SzFMV2020-Tavasz/AutomatedCar-A#216]
### Requires
- [x] #213 (add tempomat component)
- [x] #214 (add tempomat packet)
- [x] #215 (prepare powertrain for tempomat)
### Requirement For
- #218 (make tempomat follow car)

## Description
When `Tempomat` is activated, then it should remember the speed and attempt to try it constant. This requires some control techniques component with derive/integral part.

## Definition of Done
- [x] only gas and break pedal values are affected
- [x] car keeps the speed approximately
- [x] there is a stored value of target speed
- [ ] target speed can be set via setter (preparetion for #218)
