### ISSUE TITLE
Team A4 - Sprint 1 - Visualization

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2020-Tavasz/AutomatedCar-A#4]
# Vizualizáció

* Input: Objektummodell (modellezett világ), pontosabban annak elégséges metszete. A rajzoláshoz elegendőek az világot leíró állományban megtalálható adatok, nem kell megvárni a teljes modell elkészültét
* Output: Illeszkedő, résmentes megjelenítése, 24 FPS-el frissülő, folyamatos mozgás
* Challenge: Az objektumtranszformációk megfelelő végrehajtása, az objektummodellért felelős csapattal egyeztetés az objektumok elérését illetően

## Definition of Done

- [ ] A kirajzolt világ egy része látható csak állandóan a programablakban, a „kamera” a vezérelt autót (egocar) követi
    - világ széleinek kezelése
- [ ] statikus objektumok pozícióhelyes kirajzolása és illesztése a rendelkezésre álló építőelemekből
- [ ] mozgó objektumok helyes kirajzolása
- [ ] debug célból meg kell tudni jeleníteni az egyes objektumokhoz definiált poligonokat
- [ ] interfészt kell biztosítani, hogy egy megcímzett objektum poligonja eltérő színnel jelenhessen meg (ha kijelölésre kerül)
- [ ] interfészt kell biztosítani a szenzorok látóterét jelképező háromszögek opcionális megjelenítésére
- [ ] a megjelenés villódzásmentes és folyamatos legyen

## Megjegyzések

* A programablaknak az alábbi módon nézni majd ki. A kezdeti kód ezt a felosztást már támogatja, tartalmaz két JPanel-t, ebből a `CourseDisplay`re kell a világ objektumait kirajzolni. Pontosabban az a „viewport”, amit a kamera lát, mögötte ott lehet a többi objektum.
    - ha szükséges egyéb panel definiálható, de a műszerfal (dashboard) működését nem lehet megzavarni
    - ![gui_plan](https://raw.githubusercontent.com/szfmv2020-tavasz/handout/master/src/images/gui_plan_course_display.png)
* A kiadott kód csak példa alap GUI készítésére, ha a feladat úgy kívánja átírható, más rajzoló metódusok vagy logika is használható, de figyelni kell arra, hogy ez esetben minden érintett csapat tudjon a módosításokról. _Mindenek előtt a műszerfalért felelős csapat!_
* Az IntelliJ IDEA GUI Designer-e *nem* használható!

**Comment by ArchiCat** [comment]
![Problématér_team4_sprint1](https://user-images.githubusercontent.com/24422253/74945190-97fa1d00-53f7-11ea-8d43-a12aa22bbcdc.png)
