### ISSUE TITLE
Interfész Pekidzsek' Létrehozása

### ISSUE THREAD

**Issue by AbyssPrince** [SzFMV2020-Tavasz/AutomatedCar-A#57]
## Description
A megbeszélt általunk szolgáltatott adatok interfészének elkészítése, amiket majd a Virtual Function Bus-ra felteszünk.

Minél előbb kerüljön ki `master`-ra, hogy más csapatok használhassák.

## Tasks
- [x] implement vector class
- [x] add packet for car position and movement
- [x] add packet for engine status
- [x] share interfaces of packets on virtual bus publicly
