### ISSUE TITLE
Vektor Implementáció

### ISSUE THREAD

**Issue by AbyssPrince** [SzFMV2020-Tavasz/AutomatedCar-A#71]
## Description
A vektor osztályra szükség van az autó mozgásvektorának reprezentálására.

## Tasks
- [X] hossz számítása
- [X] egységvektor számítása
- [X] `vectorFromXY` factory method létrehozása az `IVector` osztályban
- [X] Tengely (`Axis` enum) pozitív és negatív irányvektorának implementálása
- [X] elforgatás radiánnal, fokkal, gradiánnal
- [X] relatív szög számítása radiánban, fokban, gradiánban
- [X] unit tesztek írása a vektor osztályra
